apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ai-inference-route
  namespace: ai-workload
  labels:
    app: ai-inference
spec:
  to:
    kind: Service
    name: ai-inference-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
